zone:
  region-id: "afk_zone-region"

  actions:
    on-enter:
      - '[message] <green>Вы вошли в AFK-зону.'
      - '[bar] <yellow>Награды начисляются автоматически.'

    on-leave:
      - '[message] <red>Вы покинули AFK-зону.'
      - '[bar] <red>Вы больше не получаете награды.'

  rewards:
    task-period-seconds: 30

    actions:
      # НЕЛЬЗЯ ДЕЛАТЬ ОДИНАКОВЫЕ ШАНСЫ!!!
      32.9:
        - '[message] <gold>Вы получили 100 монет!'
        - '[cmd] eco give {player} 100'

      33.1:
        - '[message] <green>Вы получили 1 токен!'
        - '[cmd] p give {player} 1'

      34.0:
        - '[message] <aqua>Вы получили 3 алмаза!'
        - '[cmd] give {player} diamond 3'
